@ApiRestWithNetCoreAndMongoDb_HostAddress = https://localhost:7154

GET {{ApiRestWithNetCoreAndMongoDb_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ApiRestWithNetCoreAndMongoDb_HostAddress}}/api/product

###
